// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Intel and sold by Intel or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 17.0 (Build Build 595 04/25/2017)
// Created on Fri Jan 04 17:13:39 2019

contador_16 contador_16_inst
(
	.clock(clock_sig) ,	// input  clock_sig
	.enable(enable_sig) ,	// input  enable_sig
	.reset(reset_sig) ,	// input  reset_sig
	.dieciseis(dieciseis_sig) ,	// output  dieciseis_sig
	.Q(Q_sig) 	// output [4:0] Q_sig
);

